-- MySQL Script generated by MySQL Workbench
-- Mon Mar  4 14:00:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cromartic_social
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cromartic_social
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cromartic_social` DEFAULT CHARACTER SET utf8 ;
USE `db_cromartic_social` ;

-- -----------------------------------------------------
-- Table `db_cromartic_social`.`tb_social_network_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cromartic_social`.`tb_social_network_company` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(25) NOT NULL,
  `image` NVARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cromartic_social`.`tb_social_network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cromartic_social`.`tb_social_network` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(25) NOT NULL,
  `social_network_company_id` BIGINT NOT NULL,
  `url` NVARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_social_network_tb_social_network_company_idx` (`social_network_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_social_network_tb_social_network_company`
    FOREIGN KEY (`social_network_company_id`)
    REFERENCES `db_cromartic_social`.`tb_social_network_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
