-- MySQL Script generated by MySQL Workbench
-- Wed Mar  6 13:08:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cromartic_art
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cromartic_art
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cromartic_art` DEFAULT CHARACTER SET utf8 ;
USE `db_cromartic_art` ;

-- -----------------------------------------------------
-- Table `db_cromartic_art`.`tb_art`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cromartic_art`.`tb_art` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(25) NOT NULL,
  `name` NVARCHAR(255) NOT NULL,
  `description` NVARCHAR(500) NULL,
  `image` NVARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cromartic_art`.`tb_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cromartic_art`.`tb_like` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `art_id` BIGINT NOT NULL,
  `username` VARCHAR(25) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_like_tb_art_idx` (`art_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_like_tb_art`
    FOREIGN KEY (`art_id`)
    REFERENCES `db_cromartic_art`.`tb_art` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
